build: false

environment:
  PYTHONIOENCODING: "UTF-8"

  matrix:
    - PYTHON: "C:/Python37-x64"
    - PYTHON: "C:/Python38-x64"


install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Installing Poetry
  - "curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py"
  - "python get-poetry.py -y"
  - "SET PATH=%USERPROFILE%\\.poetry\\bin;%PATH%"

  # Ensure latest pip in Poetry's virtualenv
  - "poetry run python -m pip install -U pip"

  # Install dependencies
  - "poetry install -v"

test_script:
  - "poetry run pytest --doctest-modules"
  - "poetry run coverage run"
  - "poetry run coverage report"

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -v
