# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.rst")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")

setup(
    long_description=readme,
    name="fastapi_login",
    version="0.1.0",
    description="My users route for logging in and out of a FastAPI app.",
    python_requires="==3.*,>=3.8.0",
    project_urls={
        "homepage": "https://github.com/parsd/fastapi-login",
        "repository": "https://github.com/parsd/fastapi-login",
    },
    author="Sascha Dorenbeck",
    author_email="parsd@users.noreply.github.com",
    license="MIT",
    keywords="fastapi security login",
    classifiers=[
        "Environment :: Web Environment",
        "Framework :: AsyncIO",
        "Operating System :: OS Independent",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    packages=["fastapi_login"],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        "email-validator==1.*,>=1.0.5",
        "fastapi==0.*,>=0.52.0",
        "pydantic==1.*,>=1.4.0",
        "python-multipart==0.*,>=0.0.5",
        "starlette==0.*,>=0.13.2",
        "uvicorn==0.*,>=0.11.3",
    ],
    extras_require={
        "dev": [
            "assertpy==1.*,>=1.0.0",
            "black==19.*,>=19.10.0",
            "coverage==5.*,>=5.0.3",
            "mypy==0.*,>=0.761.0",
            "pydocstyle==5.*,>=5.0.2",
            "pylint==2.*,>=2.4.4",
            "pytest==5.*,>=5.3.5",
            "pytest-clarity==0.*,>=0.3.0",
            "requests==2.*,>=2.23.0",
        ]
    },
)
